'use strict';
$_$wp(1);
let me = ($_$w(1, 0), 'Nicholas Carignan');
let description = ($_$w(1, 1), 'level 12 warlock');
let regex = ($_$w(1, 2), /a/g);
let x = ($_$w(1, 3), me.match(regex));
$_$w(1, 4), $_$tracer.log(x, 'x', 1, 4);
$_$w(1, 5), x = me.replace(/n/gi, 'Rudolf');
$_$w(1, 6), $_$wv(1, 6, '1,6', 'x', x, '$_$ne', 1, 0, '');
let y = ($_$w(1, 7), 'abghr'[3]);
$_$w(1, 8), /r/g / r / gm;
$_$wpe(1);